GET http://localhost:5000/users

###
GET http://localhost:5000/users/1

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "nom": "Boubacar Doucoure Kof",
    "login": "Bouba",
    "password": "douc"
}

###
PATCH http://localhost:5000/users/4
Content-Type: application/json

{
    "nom": " Baba Doucoure",
    "login": "Bouacar",
    "password": "douk"
}
 
###
DELETE http://localhost:5000/users/2

